# Generated by Django 4.1.3 on 2022-11-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_column='DNI TUTOR', max_length=7)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE TUTOR', max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO TUTOR', max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO TUTOR', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL TUTOR', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(db_column='ANIO')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_creacion', models.DateField(db_column='CREACION_HORARIO')),
                ('anio', models.ForeignKey(blank=True, db_column='ANIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.anio')),
            ],
        ),
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(db_column='DIA', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(db_column='DIVISION', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(db_column='ESPECIALIDADES', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=35, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=150, null=True)),
                ('objetivos', models.CharField(blank=True, db_column='OBJETIVOS', max_length=150, null=True)),
                ('contenidos', models.CharField(blank=True, db_column='CONTENIDOS', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(db_column='HORA INICIO')),
                ('hora_final', models.TimeField(db_column='HORA FINAL')),
                ('orden', models.IntegerField(db_column='ORDEN')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_column='DNI TUTOR', max_length=7)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE TUTOR', max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO TUTOR', max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO TUTOR', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL TUTOR', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(blank=True, db_column='ALUMNO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.alumno')),
                ('tutores', models.ForeignKey(blank=True, db_column='TUTORES', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaXCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_creacion', models.DateField(db_column='CREACION_HORARIO')),
                ('curso', models.ForeignKey(blank=True, db_column='CURSO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.curso')),
                ('materia', models.ForeignKey(blank=True, db_column='MATERIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.materia')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='modulo',
            field=models.ForeignKey(blank=True, db_column='DIVISION', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.modulo'),
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_column='DIA_FALTA')),
                ('hora_llegada', models.TimeField(db_column='HORA_LLEGADA')),
                ('alumno', models.ForeignKey(blank=True, db_column='ALUMNO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.alumno')),
                ('materia', models.ForeignKey(blank=True, db_column='MATERIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.materia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='division',
            field=models.ForeignKey(blank=True, db_column='DIVISION', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.division'),
        ),
        migrations.AddField(
            model_name='curso',
            name='especialidad',
            field=models.ForeignKey(blank=True, db_column='ESPECIALIDAD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.especialidad'),
        ),
        migrations.CreateModel(
            name='CronogramaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_creacion', models.DateField(db_column='CREACION_HORARIO')),
                ('curso', models.ForeignKey(blank=True, db_column='CURSO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.curso')),
                ('dia', models.ForeignKey(blank=True, db_column='DIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.diassemana')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_column='DIA')),
                ('alumno', models.ForeignKey(blank=True, db_column='ALUMNO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.alumno')),
                ('materia', models.ForeignKey(blank=True, db_column='MATERIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.materia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(blank=True, db_column='CURSO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.curso'),
        ),
    ]
