# Generated by Django 4.1.3 on 2022-11-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidosmateria',
            name='anio',
            field=models.ForeignKey(blank=True, db_column='ANIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.anio'),
        ),
        migrations.AddField(
            model_name='objetivosmateria',
            name='anio',
            field=models.ForeignKey(blank=True, db_column='ANIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='villadApp.anio'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True),
        ),
    ]
