# Generated by Django 4.1.1 on 2022-11-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villadApp', '0002_remove_cronogramacurso_horarios_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.CharField(blank=True, db_column='EMAIL TUTOR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.CharField(blank=True, db_column='EMAIL TUTOR', max_length=50, null=True),
        ),
    ]
