# Generated by Django 4.1.3 on 2022-12-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villadApp', '0003_encargadofaltas_user_profesor_user_tutor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargadofaltas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
    ]
